import Head from 'next/head'
import Link from 'next/link'
import Layout from '../components/Layout.js'

export default function Home() {
  return (
    <Layout>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1 className='wt-title'>
        Welcome to <a href="https://www.adaltas.com">web technologies!</a>
      </h1>
      <ul>
        <li>
          <Link href="/articles">
            View our articles
          </Link>
        </li>
        <li>
          <Link href="/about">
            About us
          </Link>
        </li>
        <li>
          <Link href="/contact">
            Contact us
          </Link>
        </li>
        <li>
          <Link href="/use_state">
            Use state
          </Link>
        </li>
        <li>
          <Link href="/login_native">
            Login with native elements
          </Link>
        </li>
        <li>
          <Link href="/login_controlled">
            Login with controlled elements
          </Link>
        </li>
        <li>
          Admin
          <ul>
            <li>
              <Link href="/admin/contacts">
                List of contact messages
              </Link>
            </li>
          </ul>
        </li>
      </ul>
    </Layout>
  )
}
